Update finitude.py
Added dsicharge temperature at line 130 & 131

moved HvacMonitor.FRAME_COUNT.labels out of the if statement around line 313 to elminate an error every time I send the stop comment to the Snifserver:

After Stop command I was gettign these errors:

INFO:finitude:data collection stopped
192.168.1.150 - - [08/Jun/2024 17:08:19] "GET /stop HTTP/1.1" 200 23
Exception in thread lowerlevel:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/PycharmProjects/finitude/finitude/finitude.py", line 322, in run
    HvacMonitor.FRAME_COUNT.labels(name=self.name).inc()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/PycharmProjects/finitude/venv/lib/python3.11/site-packages/prometheus_client/metrics.py", line 195, in labels
    raise ValueError('Incorrect label names')
ValueError: Incorrect label names
192.168.1.150 - - [08/Jun/2024 17:08:19] "GET /favicon.ico HTTP/1.1" 200 0


My line numbers are little different because I added many comments to my local file.